import OpenAI from 'openai';

export class OpenAIClient {
  private client: OpenAI;
  private model: string;

  constructor() {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      throw new Error('OPENAI_API_KEY environment variable is required');
    }

    this.client = new OpenAI({ apiKey });
    this.model = process.env.OPENAI_MODEL || 'gpt-4o';
  }

  async analyzeTicket(ticket: {
    summary: string;
    description: string;
    priority: string;
  }): Promise<any> {
    try {
      const prompt = `You are a senior software engineer analyzing a ticket. Break it down into actionable subtasks.

Ticket Summary: ${ticket.summary}
Description: ${ticket.description}
Priority: ${ticket.priority}

Provide a JSON response with:
{
  "summary": "Brief technical summary",
  "technicalRequirements": ["requirement1", "requirement2"],
  "subTasks": [
    {
      "id": "task-1",
      "title": "Task title",
      "description": "Detailed description",
      "estimatedComplexity": "low|medium|high",
      "dependencies": [],
      "files": ["path/to/file.ts"]
    }
  ],
  "estimatedEffort": "2-4 hours",
  "risks": ["risk1", "risk2"],
  "testingStrategy": "Testing approach"
}`;

      const response = await this.client.chat.completions.create({
        model: this.model,
        messages: [
          {
            role: 'system',
            content: 'You are a senior software engineer who analyzes tickets and breaks them into implementation tasks. Always respond with valid JSON.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
        temperature: 0.3,
        response_format: { type: 'json_object' },
      });

      const content = response.choices[0]?.message?.content;
      if (!content) {
        throw new Error('No response from OpenAI');
      }

      return JSON.parse(content);
    } catch (error) {
      console.error('Failed to analyze ticket with OpenAI', {
        error: error instanceof Error ? error.message : String(error),
        ticket: ticket.summary,
      });
      throw new Error(`OpenAI analysis failed: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  async generateCode(task: {
    title: string;
    description: string;
    files: string[];
    context?: string;
  }): Promise<Array<{ filePath: string; content: string; language: string }>> {
    try {
      const prompt = `You are a senior software engineer implementing a task. Generate complete, production-ready code.

Task: ${task.title}
Description: ${task.description}
Files to create/modify: ${task.files.join(', ')}
${task.context ? `Additional Context: ${task.context}` : ''}

Generate complete code for each file. Use this EXACT format:

### FILE: path/to/file.ts
\`\`\`typescript
// Complete file content
\`\`\`

Requirements:
- Complete, runnable code (no TODOs or placeholders)
- Proper error handling with try/catch
- TypeScript with strict types (no 'any')
- Comprehensive JSDoc comments
- Input validation
- Structured logging for errors
- Follow Next.js 14 App Router conventions if applicable`;

      const response = await this.client.chat.completions.create({
        model: this.model,
        messages: [
          {
            role: 'system',
            content: 'You are a senior software engineer who writes production-ready code. Always include complete implementations with proper error handling and types.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
        temperature: 0.2,
        max_tokens: 4000,
      });

      const content = response.choices[0]?.message?.content;
      if (!content) {
        throw new Error('No code generated by OpenAI');
      }

      return this.parseGeneratedCode(content);
    } catch (error) {
      console.error('Failed to generate code with OpenAI', {
        error: error instanceof Error ? error.message : String(error),
        task: task.title,
      });
      throw new Error(`Code generation failed: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  private parseGeneratedCode(content: string): Array<{ filePath: string; content: string; language: string }> {
    const files: Array<{ filePath: string; content: string; language: string }> = [];
    const fileRegex = /### FILE: (.+?)\n